imap <C-j> <esc>
imap <C-k> <esc>
imap { {}<LEFT>
imap ( ()<LEFT>
imap < <><LEFT>
imap [ []<LEFT>
imap <C-u> <Del>
imap <C-l> <Del>
imap <C-b> <Left>
imap <C-f> <Right>
imap <C-n> <Down>
imap <C-p> <Up>
